"""initial_schema

Revision ID: 7bc142d6ae48
Revises: 
Create Date: 2026-02-24 20:18:28.475837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc142d6ae48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_maintenance_task_status'), 'maintenance_task', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_task_task_code'), 'maintenance_task', ['task_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_task_task_code'), table_name='maintenance_task')
    op.drop_index(op.f('ix_maintenance_task_status'), table_name='maintenance_task')
    # ### end Alembic commands ###
