"""add_schedule_jobs

Revision ID: a51c12a660b6
Revises: 7bc142d6ae48
Create Date: 2026-02-24 20:25:50.763537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51c12a660b6'
down_revision: Union[str, Sequence[str], None] = '7bc142d6ae48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_schedule_jobs_job_id'), 'schedule_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_schedule_jobs_status'), 'schedule_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_jobs_status'), table_name='schedule_jobs')
    op.drop_index(op.f('ix_schedule_jobs_job_id'), table_name='schedule_jobs')
    op.drop_table('schedule_jobs')
    # ### end Alembic commands ###
